{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "sudo": false,
  "cache": {
    "pip": true
  },
  "python": [
    "2.7",
    "3.4",
    "3.5",
    "3.6",
    "3.8"
  ],
  "addons": {
    "postgresql": "9.6"
  },
  "env": {
    "jobs": [
      {
        "DATABASE_URL": "postgres://postgres:postgres@localhost:5432/orders"
      }
    ]
  },
  "install": [
    "pip install -r requirements.txt"
  ],
  "before_script": [
    "psql -c 'create database orders;' -U postgres"
  ],
  "script": [
    "python manage.py test"
  ],
  "deploy": [
    {
      "provider": "heroku",
      "strategy": "api",
      "api_key": {
        "secure": "SECURE_KEY"
      },
      "app": "CustomerOrder",
      "on": {
        "repo": "Lourine/CustomerOrder_Service",
        "branch": [
          "master"
        ]
      }
    }
  ]
}