# Generated by Django 3.1.7 on 2021-03-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersOrders', '0002_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='created',
        ),
    ]
